version: "2"
services:
  web:
    build:
      context: .
    volumes:
      - $PWD:/var/www
    ports:
      - 10000:80
    restart: always
    depends_on:
      - setup
  setup:
    image: composer:1.9.1
    volumes:
      - $PWD:/var/www
    working_dir: /var/www
    command: composer install; chmod -R 777 ./tmp; install -m 777 ./webroot/downloads
